// Generated by gencpp from file MyPackage/CustomServMessRequest.msg
// DO NOT EDIT!


#ifndef MYPACKAGE_MESSAGE_CUSTOMSERVMESSREQUEST_H
#define MYPACKAGE_MESSAGE_CUSTOMSERVMESSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace MyPackage
{
template <class ContainerAllocator>
struct CustomServMessRequest_
{
  typedef CustomServMessRequest_<ContainerAllocator> Type;

  CustomServMessRequest_()
    {
    }
  CustomServMessRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::MyPackage::CustomServMessRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::MyPackage::CustomServMessRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServMessRequest_

typedef ::MyPackage::CustomServMessRequest_<std::allocator<void> > CustomServMessRequest;

typedef boost::shared_ptr< ::MyPackage::CustomServMessRequest > CustomServMessRequestPtr;
typedef boost::shared_ptr< ::MyPackage::CustomServMessRequest const> CustomServMessRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::MyPackage::CustomServMessRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace MyPackage

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MyPackage::CustomServMessRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::MyPackage::CustomServMessRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MyPackage::CustomServMessRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::MyPackage::CustomServMessRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MyPackage/CustomServMessRequest";
  }

  static const char* value(const ::MyPackage::CustomServMessRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::MyPackage::CustomServMessRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServMessRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::MyPackage::CustomServMessRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::MyPackage::CustomServMessRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MYPACKAGE_MESSAGE_CUSTOMSERVMESSREQUEST_H
