// Generated by gencpp from file MyPackage/CustomServMess.msg
// DO NOT EDIT!


#ifndef MYPACKAGE_MESSAGE_CUSTOMSERVMESS_H
#define MYPACKAGE_MESSAGE_CUSTOMSERVMESS_H

#include <ros/service_traits.h>


#include <MyPackage/CustomServMessRequest.h>
#include <MyPackage/CustomServMessResponse.h>


namespace MyPackage
{

struct CustomServMess
{

typedef CustomServMessRequest Request;
typedef CustomServMessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomServMess
} // namespace MyPackage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::MyPackage::CustomServMess > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::MyPackage::CustomServMess&) { return value(); }
};

template<>
struct DataType< ::MyPackage::CustomServMess > {
  static const char* value()
  {
    return "MyPackage/CustomServMess";
  }

  static const char* value(const ::MyPackage::CustomServMess&) { return value(); }
};


// service_traits::MD5Sum< ::MyPackage::CustomServMessRequest> should match
// service_traits::MD5Sum< ::MyPackage::CustomServMess >
template<>
struct MD5Sum< ::MyPackage::CustomServMessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::MyPackage::CustomServMess >::value();
  }
  static const char* value(const ::MyPackage::CustomServMessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::MyPackage::CustomServMessRequest> should match
// service_traits::DataType< ::MyPackage::CustomServMess >
template<>
struct DataType< ::MyPackage::CustomServMessRequest>
{
  static const char* value()
  {
    return DataType< ::MyPackage::CustomServMess >::value();
  }
  static const char* value(const ::MyPackage::CustomServMessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::MyPackage::CustomServMessResponse> should match
// service_traits::MD5Sum< ::MyPackage::CustomServMess >
template<>
struct MD5Sum< ::MyPackage::CustomServMessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::MyPackage::CustomServMess >::value();
  }
  static const char* value(const ::MyPackage::CustomServMessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::MyPackage::CustomServMessResponse> should match
// service_traits::DataType< ::MyPackage::CustomServMess >
template<>
struct DataType< ::MyPackage::CustomServMessResponse>
{
  static const char* value()
  {
    return DataType< ::MyPackage::CustomServMess >::value();
  }
  static const char* value(const ::MyPackage::CustomServMessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPACKAGE_MESSAGE_CUSTOMSERVMESS_H
